apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.app.service.name }}
spec:
  ports:
  - port: {{ .Values.app.service.port }}
    protocol: TCP
    targetPort: {{ .Values.app.service.port }}
  selector:
    app: {{ .Values.app.name }}
  type: {{ .Values.app.service.type }}