apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Values.mysql.volume.pv.name }}
  labels:
    type: {{ .Values.mysql.volume.type }}
spec:
  storageClassName: {{ .Values.mysql.volume.storageClassName }}
  capacity:
    storage: {{ .Values.mysql.volume.storage }}
  accessModes:
    - {{ .Values.mysql.volume.accessModes }}
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: {{ .Values.mysql.volume.hostPath }}

