apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.mysql.volume.pvc.name }}
spec:
  storageClassName: {{ .Values.mysql.volume.storageClassName }}
  accessModes:
    - {{ .Values.mysql.volume.accessModes }}
  resources:
    requests:
      storage: {{ .Values.mysql.volume.storage }}